# Action that periodically fetches commits from the upstream to update our app source data.

name: Auto-Update Data

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  auto-update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0

      - name: Add upstream
        run: git remote add upstream git@github.com:CSSEGISandData/COVID-19.git

      - name: Fetch upstream master
        run: git fetch upstream master

      - name: Set committing user to "Github Action"
        run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"

      - name: Merge upstream master into local master
        run: |
          git merge upstream/master -m "Auto-sync changes from upstream
          `git log -1`"

      - name: Install project modules in preparation for data build script run
        run: npm install

      - name: Rebuild source data from latest datasets
        run: node ./src/scripts/build-data-files.js

      - name: Commit updated source data
        run: git add ./src/data/ && git commit -m "Auto-rebuild src/data files" || echo "Skipping commit because there are no changes to commit."

      - name: Push master
        run: git push
